name: Test, Build and release

on:
  push:
    branches: [ Build_APK ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      
    - name: Use Java11
      uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '11'

    - name: Build debug apk
      run: ./gradlew clean assembleDebug

    - name: Create release and upload apk
      uses: ShaunLWM/action-release-debugapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       APP_FOLDER: app
       RELEASE_TITLE: New Build
